import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "@/components/custom/NavBar";
import CartProvider from "@/components/providers/CartProvider";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <CartProvider>
                    <NavBar />

                    <main className="min-h-[calc(100vh-73px)] mt-12">
                        {children}
                    </main>

                    <Toaster />
                </CartProvider>
            </body>
        </html>
    );
}

export default RootLayout;
